version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/node:16

jobs:
  screenshot:
    executor: ubuntu-executor
    working_directory: /tmp/project  # Use a specific subdirectory under /tmp
    steps:
      - checkout  # Step to checkout your code from GitHub

      - run:
          name: Install Puppeteer
          command: |
            npm install puppeteer

      - run:
          name: Ensure Script Permissions
          command: chmod +x ./script.js  # Ensure script.js is executable

      - run:
          name: Run Puppeteer Script
          command: node ./script.js  # Run the script from the working directory

      - run:
          name: Move Artifacts
          command: |
            mkdir -p screenshots  # Ensure the screenshots directory exists
            mv screenshots/screenshot.jpg screenshots/  # Move the screenshot
            mv accounts.txt screenshots/  # Move the accounts.txt

      - store_artifacts:
          path: screenshots/screenshot.jpg
          destination: screenshot

      - store_artifacts:
          path: screenshots/accounts.txt
          destination: accounts

      - store_artifacts:
          path: screenshots/
          destination: screenshots-directory

workflows:
  version: 2
  build:
    jobs:
      - screenshot
