version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/node:16

jobs:
  screenshot:
    executor: ubuntu-executor
    working_directory: /tmp/project  # Use a specific subdirectory under /tmp
    steps:
      - checkout  # Step to checkout your code from GitHub

      - run:
          name: Install Dependencies for Puppeteer
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libnss3 \
              libgconf-2-4 \
              libxss1 \
              libasound2 \
              fonts-liberation \
              libatk-bridge2.0-0 \
              libgtk-3-0 \
              libx11-xcb1 \
              libxcomposite1 \
              libxcursor1 \
              libxrandr2 \
              libxdamage1 \
              libxi6 \
              libxtst6 \
              libxss1 \
              libnss3-dev \
              libx11-dev \
              libgdk-pixbuf2.0-dev \
              libglib2.0-dev

      - run:
          name: Install Puppeteer
          command: npm install puppeteer

      - run:
          name: Ensure Script Permissions
          command: chmod +x ./script.js  # Ensure script.js is executable

      - run:
          name: Run Puppeteer Script
          command: node ./script.js  # Run the script from the working directory

      - run:
          name: Move Artifacts
          command: |
            mkdir -p screenshots  # Ensure the screenshots directory exists
            mv screenshot-*.jpg screenshots/  # Move all screenshots
            mv accounts.txt screenshots/  # Move the accounts.txt

      - store_artifacts:
          path: screenshots/
          destination: screenshots-directory

workflows:
  version: 2
  build:
    jobs:
      - screenshot
