version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/node:16

jobs:
  screenshot:
    executor: ubuntu-executor
    working_directory: /tmp  # Use /tmp as the working directory
    steps:
      - checkout

      - run:
          name: Install Puppeteer
          command: npm install puppeteer

      - run:
          name: Run Puppeteer Script
          command: node script.js

      - run:
          name: Create Dummy Artifacts
          command: |
            mkdir -p /tmp/screenshots  # Ensure the screenshots directory exists
            echo "my artifact file" > /tmp/screenshots/artifact-1.txt
            mkdir -p /tmp/screenshots/artifacts
            echo "my artifact files in a dir" > /tmp/screenshots/artifacts/artifact-2.txt

      - store_artifacts:
          path: /tmp/screenshots/artifact-1.txt
          destination: artifact-file

      - store_artifacts:
          path: /tmp/screenshots/artifacts
          destination: artifacts-dir

workflows:
  version: 2
  build:
    jobs:
      - screenshot
