version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/node:16

jobs:
  screenshot:
    executor: ubuntu-executor
    working_directory: /tmp/project  # Use a specific subdirectory under /tmp
    steps:
      - checkout  # Step to checkout your code from GitHub

      - run:
          name: Install Puppeteer
          command: npm install puppeteer

      - run:
          name: Move Script
          command: cp script.js ./script.js  # Copy script.js to the working directory

      - run:
          name: Run Puppeteer Script
          command: node script.js  # Run the script from the working directory

      - run:
          name: Create Dummy Artifacts
          command: |
            mkdir -p screenshots  # Ensure the screenshots directory exists
            echo "my artifact file" > screenshots/artifact-1.txt
            mkdir -p screenshots/artifacts
            echo "my artifact files in a dir" > screenshots/artifacts/artifact-2.txt

      - store_artifacts:
          path: screenshots/artifact-1.txt
          destination: artifact-file

      - store_artifacts:
          path: screenshots/artifacts
          destination: artifacts-dir

workflows:
  version: 2
  build:
    jobs:
      - screenshot
