name: Puppeteer Screenshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Brave and Puppeteer
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -qO - https://brave-browser-archive.s3.brave.com/brave-core.asc | sudo apt-key add -
          echo "deb [arch=amd64] https://brave-browser-archive.s3.brave.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/brave.list
          sudo apt update
          sudo apt install -y brave-browser
          npm install puppeteer

      - name: Run Puppeteer Script
        run: |
          node script.js

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
