name: Puppeteer Screenshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Run Puppeteer Script
        run: |
          node script.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.jpg
