name: Puppeteer Screenshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y firefox \
            libdbus-glib-1-2 \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libxrandr2 \
            libxss1 \
            libasound2 \
            libatk1.0-0 \
            libgdk-pixbuf2.0-0 \
            libpango-1.0-0 \
            libcups2

      - name: Install Puppeteer
        run: |
          npm install puppeteer puppeteer-firefox

      - name: Run Puppeteer Script
        run: |
          node script.js

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
