name: Puppeteer Screenshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Run Puppeteer Script
        run: |
          mkdir -p chrome-profile
          echo "const puppeteer = require('puppeteer');" > script.js
          echo "const { setTimeout } = require('node:timers/promises');" >> script.js
          echo "async function run() {" >> script.js
          echo "  const browser = await puppeteer.launch({ headless: true, userDataDir: './chrome-profile' });" >> script.js
          echo "  const page = await browser.newPage();" >> script.js
          echo "  await page.goto('https://emailnator.com');" >> script.js
          echo "  await setTimeout(3000); // Wait for 4 seconds to ensure page loads" >> script.js
          echo "  const email = await page.$eval('input[placeholder="Email Address"]', el => el.value);" >> script.js
          echo "  console.log('Extracted email:', email);" >> script.js
          echo "  await page.goto('https://www.alwaysdata.com');" >> script.js
          echo "  await setTimeout(3000); // Wait for 3 seconds before clicking the button" >> script.js
          echo "  await page.click('a.btn.free[href=\"/en/register/?d\"]');" >> script.js
          echo "  await setTimeout(3000); // Wait for 4 seconds to let the next page load" >> script.js
          echo "  await page.waitForSelector('input[name=\"email\"]');" >> script.js
          echo "  await page.type('input[name=\"email\"]', email);" >> script.js
          echo "  await setTimeout(3000); // Wait for 4 seconds to let the next page load" >> script.js
          echo "  await page.screenshot({ path: 'screenshot.jpg', type: 'jpeg' });" >> script.js
          echo "  await browser.close();" >> script.js
          echo "}" >> script.js
          echo "run();" >> script.js
          node script.js

      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.jpg
